config/routes.rb
Rails.application.routes.draw do
  get 'report/award'
  resources :cars
  resources :routes
  resources :licensees
  resources :criteria
  resources :datafiles
  resources :attachments do
    member do
      get 'remove'
    end
  end
  resources :criteria_groups
  resources :violations
  resources :logs
  resources :public_comments, except: :edit do
    collection do
      get 'application/:application_id', to: 'public_comments#application'
    end
  end
  resources :announcements do
    member do
      get 'publish'
      delete 'main_attachment', to: 'announcements#delete_main_attachment', as: 'delete_main_attachment'
      delete 'other_attachments/:attachment_id', to: 'announcements#delete_other_attachments', as: 'delete_other_attachments'
    end
  end
  get 'public_announcement', to: 'announcements#lists'
  get 'add_comment', to: 'public_comments#add_comment'
  post 'add_comment', to: 'public_comments#add_comment_post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'static_pages/test1'

  resources :users
  get 'users/:id/edit_profile', to: 'users#edit_profile', as: 'profile_edit_user'
  patch 'users/:id/edit_profile', to: 'users#update_profile'


  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  #session
  get 'register', to: 'sessions#register'
  post 'register', to: 'sessions#register_post'
  get 'login(/:options)', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'profile', to: 'sessions#profile'

  resources :applications do
    member do
      get 'apply_step1'
      get 'apply_step2'
      get 'apply_step3'
      get 'fail_self_evaluation'
      post 'apply_step1', to: 'applications#post_step1'
      post 'apply_step2', to: 'applications#post_step2'
      post 'apply_step3', to: 'applications#post_step3'

      post 'add_car', to: 'applications#add_car'
      delete 'remove_car/:car_id', to: 'applications#remove_car', as: 'remove_car'

      get 'add_evidences'
      post 'add_attachment'
      get 'finish_add_evidences'
      get 'extend_from'
      get 'show_full'
    end
    collection do
      get 'apply'
      get 'extend'
      post 'apply', to: 'applications#post_apply'
      get 'dashboard'
      get 'finished'
      get 'in_progress'
    end
  end

  resources :evaluations

  #process
  get  'process/dashboard'

  get  'process/registers',       to: 'process#registered_index'
  get  'process/register/:id',    to: 'process#registered', as: 'process_register'
  post 'process/register/:id',    to: 'process#registered_post', as: 'confirm_process_register'

  get  'process/appointments',    to: 'process#appointment_index'
  get  'process/appointment_form'
  get  'process/appointment/visit/:id', to: 'process#appointment_visit', as: 'appointment_visit'
  post 'process/appointment/visit/:id', to: 'process#appointment_visit_post'
  post 'process/appointment',     to: 'process#appointment_post', as: 'appoint_process_appointment'
  get  'process/appointed/:id',   to: 'process#appointed', as: 'process_appointed'

  get  'process/verifications',   to: 'process#verification_index'
  get  'process/verification/:id',to: 'process#verification', as: 'process_verify'
  post 'process/verification/:id',to: 'process#verification_post'

  get  'process/evaluations',     to: 'process#evaluation_index'
  get  'process/evaluation/:id',  to: 'process#evaluation', as: 'process_evaluation'
  post 'process/evaluation/:id',  to: 'process#evaluation_post'
  post 'process/evaluation/:id/finish',  to: 'process#evaluation_finish', as: 'process_evaluation_finish'
  post 'process/evaluation/:id/reject',  to: 'process#evaluation_reject', as: 'process_evaluation_reject'

  get  'process/awards',          to: 'process#award_index'
  get  'process/award/:id',       to: 'process#award', as: 'process_award'
  post 'process/award/:id',       to: 'process#award_post'


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.haml
.carousel.carousel-slider.center
  - Announcement.where("priority > 0").order(:priority).each do |ann|
    .carousel-item.purple.white-text{href: "#one!"}
      = raw ann.description

  /  .container{style: 'width: 70% !important'}
  /    %p.white-text{style: 'font-size: 2.28rem;'}
  /      เปิดรับสมัครเข้าร่วมโครงการ Q-BUS
  /      รุ่นที่ 1 ประจำปี 2562
  /    %h5.white-text
  /      ขอเชิญผู้ประกอบการขนส่งรถโดยสารสาธารณะสมัครเข้าร่วมโครงการ
  /      %br
  /      ได้ตั้งแต่วันที่ 1 เม.ย. 2562 ถึง 15 พ.ค. 2562
  /      %br
  /      สอบถามรายละเอียดเพิ่มเติม: 02-271-8503
  /      %br
  /      %br
  /    = link_to 'สมัครเข้าร่วมโครงการ', apply_applications_path, class: 'btn gradient-45deg-deep-orange-orange border-round'
  /.carousel-item.purple.white-text{href: "#two!"}
  /  %h2.white-text ข่าวประชาสัมพันธ์ 1
  /.carousel-item.purple.white-text{href: "#three!"}
  /  %h2.white-text ข่าวประชาสัมพันธ์ 2
.container{style: 'width: 70% !important;'}
  = render 'layouts/flash'
  .row#left-menu
    - if !logged_in?
      .col.s12.m4
        .card.border-radius-6
          .card-content
            = simple_form_for(:session, :url => login_path, :method => :post) do |f|
              .card-title
                %h4 เข้าสู่ระบบ
              .row
                .input-field.col.s12
                  %i.material-icons.prefix person_outline
                  = f.input_field :email
                  = f.label :email
              .row
                .input-field.col.s12
                  %i.material-icons.prefix lock_outline
                  = f.input_field :password
                  = f.label :password, 'รหัสผ่าน'
              .row
                .input-field.col.s12
                  %p
                    = f.label :remember_me  do
                      = f.input_field :remember_me, as: :boolean
                      %span= t(:remember_me)
              .row
                .input-field.col.s12
                  = f.submit 'เข้าสู่ระบบ', class: 'btn border-round col s12 gradient-45deg-purple-deep-purple'
              .row
                .input-field.col.s6
                  %p.margin.medium-small
                    = link_to 'สมัครใช้งาน', register_path
                .input-field.col.s6
                  %p.margin.right-align.medium-small
                    = link_to 'ลืมรหัสผ่าน', new_password_reset_path
    - else
      .col.s12.m4
        .card.border-radius-6
          .card-content.center
            %h5 ยินดีต้อนรับ
            %h5 คุณ #{@current_user.name}
          .card-action.center
            = link_to 'ไปยังหน้าหลัก', process_dashboard_path, class: 'btn border-round col s12 gradient-45deg-deep-orange-orange waves-effect waves-light'
            %br
            %br
            = link_to 'สมัครเข้าร่วมโครงการ', apply_applications_path, class: 'btn border-round col s12 gradient-45deg-green-teal waves-effect waves-light'
            %br
            %br
            = link_to 'ต่ออายุ', extend_applications_path, class: 'btn border-round col s12 gradient-45deg-green-teal darken-1 waves-effect waves-light'
            %br
            %br
            %a{"href" => "logout", "data-method" => "delete", class: 'btn border-round col s12 gradient-45deg-red-pink darken-1 waves-effect waves-light'}
              ออกจากระบบ
            %br
            %br
    .col.s12.m8
      .row
        .col.s12.m6
          .card.small
            .card-content
              .card-title
                %h5 ส่งข้อคิดเห็นหรือเรื่องร้องเรียน
              ผู้ใช้บริการรถโดยสารสาธารณะ สามารถให้ช้อคิดเห็นหรือ ส่งเรื่องร้องเรียนด้านการให้บริการได้
            .card-action
              .center
                = link_to 'ส่งข้อคิดเห็น', add_comment_path, class: 'btn border-round gradient-45deg-deep-orange-orange waves-effect waves-light'
        .col.s12.m6
          .card.small
            .card-content
              .card-title
                %h5 ตรวจสอบรายชื่อผู้ได้รับรางวัล
              ผู้ใช้บริการรถโดยสารสาธารณะ สามารถตรวจสอบรายชื่อผู้ประกอบการหรือเส้นทางที่ได้รับรางวัลได้
            .card-action
              .center
                = link_to 'ตรวจสอบผู้ได้รับรางวัล', report_award_path, class: 'btn border-round gradient-45deg-deep-orange-orange waves-effect waves-light'

      .card
        .card-content
          .card-title
            %h5 เอกสารที่เกี่ยวข้อง
          .row
            .col.s4.center
              %a{href: '/form/คู่มือการใช้งาน.pdf'}
                %i.material-icons{style: 'font-size: 3rem;'} library_books
                %br
                คู่มือการใช้งาน

            .col.s4.center
              %a{href: '/form/แบบสำรวจข้อมูลประกอบการขนส่ง.pdf'}
                %i.material-icons{style: 'font-size: 3rem;'} list
                %br
                แบบการตรวจประเมินหน้างาน
            .col.s4.center
              %a
                %i.material-icons{style: 'font-size: 3rem;'} question_answer
                %br
                คำถามพบบ่อย
          .row
            .col.s4.center
              %a{href: '/form/หนังสือยืนยันการเข้าร่วม Q-Bus.docx'}
                %i.material-icons{style: 'font-size: 3rem;'} done_all
                %br
                แบบยืนยันการเข้าร่วมโครงการ
            .col.s4.center
              %a{href: '/form/ตัวอย่างเอกสารประกอบการประเมิน.pdf'}
                %i.material-icons{style: 'font-size: 3rem;'} insert_drive_file
                %br
                ตัวอย่างเอกสารประกอบการประเมิน
            .col.s4.center

  .row
    .col.s12
      %h4 ข่าวประชาสัมพันธ์
  .row
    - Announcement.where(priority: 0).last(3).each do |announcement|
      .col.m4
        .card.medium
          - if announcement.main_attachment.attached? && announcement.main_attachment&.representable?
            .card-image{style: 'background-color: white;'}
              = image_tag rails_representation_url(announcement.main_attachment.representation(resize: '320x240'))
              %span.card-title{style: 'background-color: purple; font-weight: bold; padding: 10px'}
                = announcement.title
          - else
            .card-image{style: 'height: 340px; background-color: white;'}
              %span.card-title{style: 'background-color: purple; font-weight: bold; padding: 10px'}
                = announcement.title
          .card-content{style: 'height: 5rem; overflow: hidden; padding: 10px'}
            = raw announcement.description
          .card-action
            %a{:href => publish_announcement_path(announcement)}
              อ่านต่อ




:javascript
  $('.carousel.carousel-slider').carousel({
    fullWidth: true,
    indicators: true
  });