config/routes.rb
Rails.application.routes.draw do
  get 'report/award'
  resources :cars
  resources :routes
  resources :licensees
  resources :criteria
  resources :datafiles
  resources :attachments do
    member do
      get 'remove'
    end
  end
  resources :criteria_groups
  resources :violations
  resources :logs
  resources :public_comments, except: :edit do
    collection do
      get 'application/:application_id', to: 'public_comments#application'
    end
  end
  resources :announcements do
    member do
      get 'publish'
      delete 'main_attachment', to: 'announcements#delete_main_attachment', as: 'delete_main_attachment'
      delete 'other_attachments/:attachment_id', to: 'announcements#delete_other_attachments', as: 'delete_other_attachments'
    end
  end
  get 'public_announcement', to: 'announcements#lists'
  get 'add_comment', to: 'public_comments#add_comment'
  post 'add_comment', to: 'public_comments#add_comment_post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'static_pages/test1'

  resources :users
  get 'users/:id/edit_profile', to: 'users#edit_profile', as: 'profile_edit_user'
  patch 'users/:id/edit_profile', to: 'users#update_profile'


  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  #session
  get 'register', to: 'sessions#register'
  post 'register', to: 'sessions#register_post'
  get 'login(/:options)', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'profile', to: 'sessions#profile'

  resources :applications do
    member do
      get 'apply_step1'
      get 'apply_step2'
      get 'apply_step3'
      get 'fail_self_evaluation'
      post 'apply_step1', to: 'applications#post_step1'
      post 'apply_step2', to: 'applications#post_step2'
      post 'apply_step3', to: 'applications#post_step3'

      post 'add_car', to: 'applications#add_car'
      delete 'remove_car/:car_id', to: 'applications#remove_car', as: 'remove_car'

      get 'add_evidences'
      post 'add_attachment'
      get 'finish_add_evidences'
      get 'extend_from'
      get 'show_full'
    end
    collection do
      get 'apply'
      get 'extend'
      post 'apply', to: 'applications#post_apply'
      get 'dashboard'
      get 'finished'
      get 'in_progress'
    end
  end

  resources :evaluations

  #process
  get  'process/dashboard'

  get  'process/registers',       to: 'process#registered_index'
  get  'process/register/:id',    to: 'process#registered', as: 'process_register'
  post 'process/register/:id',    to: 'process#registered_post', as: 'confirm_process_register'

  get  'process/appointments',    to: 'process#appointment_index'
  get  'process/appointment_form'
  get  'process/appointment/visit/:id', to: 'process#appointment_visit', as: 'appointment_visit'
  post 'process/appointment/visit/:id', to: 'process#appointment_visit_post'
  post 'process/appointment',     to: 'process#appointment_post', as: 'appoint_process_appointment'
  get  'process/appointed/:id',   to: 'process#appointed', as: 'process_appointed'

  get  'process/verifications',   to: 'process#verification_index'
  get  'process/verification/:id',to: 'process#verification', as: 'process_verify'
  post 'process/verification/:id',to: 'process#verification_post'

  get  'process/evaluations',     to: 'process#evaluation_index'
  get  'process/evaluation/:id',  to: 'process#evaluation', as: 'process_evaluation'
  post 'process/evaluation/:id',  to: 'process#evaluation_post'
  post 'process/evaluation/:id/finish',  to: 'process#evaluation_finish', as: 'process_evaluation_finish'
  post 'process/evaluation/:id/reject',  to: 'process#evaluation_reject', as: 'process_evaluation_reject'

  get  'process/awards',          to: 'process#award_index'
  get  'process/award/:id',       to: 'process#award', as: 'process_award'
  post 'process/award/:id',       to: 'process#award_post'


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #THIS IS THE BASE CLASE
  #  NOT THE RESOURCE "Applications"
  #
  #  My fault... should not name the resource as "applications"

  before_action :set_locale

  before_action :current_user

  def set_locale
    I18n.locale = I18n.default_locale
  end

  protect_from_forgery with: :exception

  include SessionsHelper

  def logged_in_user
    unless logged_in?
      redirect_to login_url, flash: {error: 'ท่านต้องเข้าสู่ระบบก่อนกระทำรายการดังกล่าว'}
    end
  end

  def admin_authorization
    unless @current_user &&  @current_user.is_admin?
      redirect_to root_path, flash: {error: 'ท่านไม่มีสิทธิ์ในการทำรายการดังกล่าว'}
    end
  end

  def has_licensee_role
    unless logged_in? && @current_user.has_role(:licensee)
      redirect_to root_path, flash: {error: 'ท่านไม่มีสิทธิ์ในการทำรายการดังกล่าว'}
    end
  end

  def logged_in_with_role(roles =[])
    unless logged_in?
      redirect_to login_url, flash: {error: 'ท่านต้องเข้าสู่ระบบก่อนกระทำรายการดังกล่าว'}
      return
    end

    pass = false
    roles.each do |role|
      if @current_user.has_role(role)
        pass=true
        break
      end
    end

    unless pass
      redirect_to root_path, flash: {error: 'ท่านไม่มีสิทธิ์ในการทำรายการดังกล่าว'}
    end
  end

  def can_access_app_by_province(application)
    return true if @current_user.is_admin? || @current_user.all_provinces?
    if st = application.license_no[0..1] != @current_user.province
      redirect_to root_path, flash: {error: "ท่านไม่มีสิทธิ์ในการเข้าถึงใบสมัครหมายเลข #{application.id_text}"}
      return false
    end
    return true
  end

  def owner_or_admin
    unless logged_in? && (@current_user.is_admin? || @current_user == @application.user)
      redirect_to root_path, flash: {error: 'ท่านไม่มีสิทธิ์ในการทำรายการดังกล่าว'}
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  FLASH_MSG_CLASS = {
    success: 'green lighten-4',
    error: 'red lighten-4',
    alert: 'orange lighten-4',
    notice: 'light-blue lighten-4'
  }

  FLASH_MSG_TEXTCOLOR = {
    success: 'green-text',
    error: 'red-text',
    alert: 'orange-text',
    notice: 'deep-purple-text darken-3',
  }
  def flash_class(flash_type)
    FLASH_MSG_CLASS.fetch(flash_type.to_sym, flash_type.to_s)
  end

  def flash_textcolor(flash_type)
    FLASH_MSG_TEXTCOLOR.fetch(flash_type.to_sym, flash_type.to_s)
  end

  def ldate(dt, hash = {})
    dt ? l(dt, hash) : nil
  end

  def thai_year(date, format = '%d %b tYYYY')
    return '' unless date && format
    format.gsub!('tYYYY', (date.year.to_i+543).to_s)
    format.gsub!('tYY', ((date.year.to_i+543) % 100).to_s)

    localize date, format: format
  end
end

app/helpers/applications_helper.rb
module ApplicationsHelper
  def progress_bar(app)
    width = 5
    case app.state
    when 'applying'
      width = 10
    when 'registered'
      width = 20
    when 'confirmed'
      width = 50
    when 'submitted'
      width = 75
    when 'evaluated'
      width = 90
    when 'awarded'
      width = 100
    end

    render partial: 'applications/field/progress_bar', locals: {width: width}
  end

  def state_full(app)
    case app.state
    when 'applying'
      text_color = 'light-blue-text'
    when 'registered'
      text_color = 'orange-text'
    when 'confirmed'
      text_color = 'pink-text'
    when 'submitted'
      text_color = 'lime-green-text'
    when 'evaluated'
      text_color = 'brown-text'
    when 'awarded'
      text_color = 'black-text'
    end

    a = render partial: 'applications/field/state', locals: {text_color: text_color, state_text: app.state_text}
    b = progress_bar(app)
    return a+b
  end

  def tri_word(value, yes_value, no_value, nil_value)
    return nil_value if value.nil?
    return no_value if value.to_s == '0'
    return yes_value
  end

  def final_award_text(app)
    if app.award_won.nil?
      'ยังไม่ได้ตัดสินผล'
    elsif app.award_won
      tag.span 'ได้มาตรฐาน Q-BUS', class: 'green-text'
    else
      tag.span 'ไม่ได้มาตรฐาน', class: 'red-text'
    end
  end
end

app/views/applications/_cars.html.haml
.row
  .col.s12
    %h6 เอกสาร ขส.บ.11
    - if @application.get_attachment(:b11)
      = download_link @application.get_attachment(:b11), nil_text: nil
    - else
      ไม่มีการแนบ ขส.บ.11
.row
  .col.s12
    .dataTables_wrapper
      %table#car_table
        %thead
          %tr
            %th= t :province, scope: 'activerecord.attributes.car'
            %th= t :plate, scope: 'activerecord.attributes.car'
            %th= t :brand, scope: 'activerecord.attributes.car'
            -# %th= t :chassis, scope: 'activerecord.attributes.car'
            %th= t :car_type, scope: 'activerecord.attributes.car'
            %th
        %tbody
          - @application.cars.each do |car|
            %tr
              %td= car.province
              %td= car.plate
              %td= car.brand
              -# %td= car.chassis
              %td= car.car_type
              %td

app/views/applications/_current_apply_step.html.haml
%h5 วิธีการสมัคร
%ul.collection
  %li.collection-item
    1. เลือกหมวดการเดินรถ
  %li.collection-item
    2. กรอกข้อมูลพื้นฐาน
  %li.collection-item
    3. กรอกข้อมูลรถ
  %li.collection-item
    4. ทำแบบประเมินตนเอง

app/views/applications/_licensee.html.haml
.row
  .col.s12
    %p
      %h6= t(:name, scope: 'activerecord.attributes.licensee')
      = @application.licensee.name
    %p
      %h6= t(:license_no, scope: 'activerecord.attributes.licensee')
      = @application.licensee.license_no

app/views/applications/_route.html.haml
.row
  .col.s6
    - unless @application.category3?
      %p
        %h6= t(:route_no, scope: 'activerecord.attributes.route')
        = @application.route_no
      %p
        %h6= t(:start, scope: 'activerecord.attributes.route')
        = @application.route_start
      %p
        %h6= t(:destination, scope: 'activerecord.attributes.route')
        = @application.route_destination
    - else
      %p
        %h6 ไม่ประจำทาง
  .col.s6
    - unless @application.category3?
      %p
        %h6= 'จำนวนรถที่มีอยู่จริง (คัน)'
        = @application.car_count || "ไม่ระบุ"
      %p
        %h6= 'จำนวนเที่ยวเดินรถจริงเฉลี่ยต่อวัน (เที่ยว)'
        = @application.trip_count || "ไม่ระบุ"

app/views/applications/add_evidences.html.haml
.row
  .col.s12
    .card
      .card-content
        .card-title
          %h4 ส่งหลักฐานสำหรับการประเมิน ใบสมัครหมายเลข #{@application.id}

        .section
          .row
            .col.s12.m8
              = render partial: "applications/application"
            .col.s12.m4
              .card.gradient-45deg-light-green-amber
                .card-content
                  ใบสมัครนี้ได้รับการประเมินเบื้องต้นแล้ว ให้ผู้สมัครทำการนำส่งหลักฐานในหัวข้อต่าง ๆ ต่อไปนี้โดยให้ส่งเป็นไฟล์ประเภท pdf 
.row
  .col.s12.m4.push-m8
    .card.gradient-45deg-light-green-amber
      .card-content
        .card-title
          %h6 วิธีใช้งาน
        การส่งไฟล์ทำได้โดยเลือก "ประเภทของไฟล์" จากนั้นให้กดปุ่ม "เลือกไฟล์" แล้วเลือกไฟล์ที่ต้องการ เมื่อเลือกแล้วให้กดปุ่ม "ส่ง"
        %br
        %br
        เมื่อแนบหลักฐานทั้งหมดแล้ว ให้กดปุ่ม "ยืนยันหลักฐาน"
  .col.s12.m8.pull-m4
    .card
      = simple_form_for @attachment, url: add_attachment_application_path(@application), method: :post , html: { class: 'form_validate', multipart: true } do |f|
        .card-content
          %h4 ส่งหลักฐาน
          .row
            .input-field.col.s12
              - #= f.input_field :criterium_attachment_id, data: {constrainwidth: 'false'}, collection: @application.sorted_attachments.map {|x| ["(#{x.criterium_attachment.criterium.name}) #{x.criterium_attachment.name}",x.criterium_attachment_id] }
              = f.input_field :evidence_id, data: {constrainwidth: 'false'},  collection: Evidence.all.each.map {|x| ["#{x.first_cri_num} #{x.name}",x.id] }, class: 'required'
              = f.label 'ประเภทหลักฐาน'
          .row
            .col.s12
              .input-field.file-field
                .btn.green
                  %span เลือกไฟล์
                  = f.file_field :data
                .file-path-wrapper
                  = f.input_field :filename, class: 'file-path validate'
          .row
            .col.s12
              = f.button :submit, 'ส่งไฟล์แนบ', class: "btn waves-light left green"
          .section
          .row
            .col.s6
              กรุณาส่งหลักฐาน โดยใช้ไฟล์ในรูปแบบ
              %span.strong pdf, doc, jpg หรือ png เท่านั้น
              และไฟล์ดังกล่าวจะต้องเห็นรายละเอียดได้ชัดเจน
      -#.card-action
      -#  %button.btn.waves-effect.waves-light.green.modal-trigger{ data: {target: 'copy-evidence'}} ใช้หลักฐานจากใบสมัครอื่น
      -#  %br
      -#  ในกรณีที่ท่านได้เคยแนบหลักฐานมาก่อนหน้านี้ในใบสมัครอื่น ๆ ท่านสามารถใช้หลักฐานที่ได้เคยส่งมาแล้วมาเป็นหลักฐานสำหรับใบสมัครปัจจุบันนี้ได้เลย
      .card-action
        ท่านได้ส่งเอกสารมาแล้ว 
        %span.strong #{@missing[:present]}
        เอกสาร จากที่ต้องการทั้งหมด
        %span.strong #{@missing[:total]}
        เอกสาร
        %ul
          - last_cg = nil
          - CriteriaGroup.need_evidence.each do |cg|
            %li{style:  'list-style-type: circle !important; margin-left: 3rem;'}
              #{cg.name}
              - if @missing[cg.id][:ok]
                %span.green-text หลักฐานครบแล้ว
              - else
                %span.red-text ส่งมาแล้ว #{@missing[cg.id][:present]} จาก #{@missing[cg.id][:total]}
        - if @missing[:present] != @missing[:total]
          ยังมีเกณฑ์การประเมินที่แนบเอกสารไม่ครบ ผู้ประเมินอาจพิจารณาไม่ให้คะแนนสำหรับเกณฑ์ข้อนั้นๆ ได้
        .section
        = link_to 'ยืนยันหลักฐาน', finish_add_evidences_application_path(@application), class: 'btn waves-effect waves-light gradient-45deg-purple-deep-purple', data: {confirm: 'เมื่อยืนยันแล้ว จะไม่สามารถแก้ไขเพิ่มเติมหลักฐานได้อีก ท่านจะยืนยันหรือไม่?'}
:css
  .tabs .tab a:hover {
    color: white;
    background-color: rgba(38, 166, 154, 0.2);
    /*Custom Color On Hover*/
  }

  .tabs .tab a:focus.active {
    color:#26a69a;
    /*Custom Text Color While Active*/
    background-color: rgba(38, 166, 154, 0.8);
    /*Custom Background Color While Active*/
  }

  .tabs .indicator {
    /*background-color:#26a69a;*/
    color: black;
    background-color: black;
    /*Custom Color Of Indicator*/
  }

.row
  .col.s12
    .card.teal.lighten-4
      .card-content
        .card-title
          %h4 รายการหลักฐาน
      .card-tabs
        %ul.tabs.tabs-fixed-width.tabs-transparent
          - last_cg = nil
          - CriteriaGroup.need_evidence.each do |cg|
            %li.tab.black-text
              %a.black-text{href: "#tab_cg#{cg.id}"}
                #{cg.name_trim}
                - if @missing[cg.id][:ok]
                  (หลักฐานครบ)
                - else
                  (#{@missing[cg.id][:present]}/#{@missing[cg.id][:total]})
      - CriteriaGroup.need_evidence.each do |cg|
        %div{ id: "tab_cg#{cg.id}"}
          .card-content.teal.lighten-5
            = render partial: "process/evidence", locals: {cgroups: [cg],enable_delete: true}


#copy-evidence.modal
  = form_with url: add_car_application_path(@application), local: true do |f|
    .modal-content
      %h4 คัดลอกหลักฐานจากใบสมัครอื่น
      %p
        ท่านได้เคยทำใบสมัครที่ได้กรอกข้อมูลของผู้ประกอบการต่อไปนี้ไว้แล้ว ให้กดปุ่ม "คัดลอก" เพื่อนำเอาหลักฐานจากใบสมัครที่เลือกมาใช้เป็นหลักฐานในใบสมัครปัจจุบัน
      %p
        ท่านสามารถเพิ่มหลักฐานอื่นได้อีกหลังจากทำการคัดลอกแล้ว
    .modal-footer
      %a.modal-close.waves-effect.wave-flat.btn-flat{href: "#!"} ยกเลิก

app/views/applications/apply.html.haml
.row
  .col.s12
    .card
      .card-content
        .card-title
          %h3 สมัครเข้าร่วมโครงการ Q-BUS
        .row
          .col.s12.m3
            = render "current_apply_step"
          .col.s12.m9
            %h4 เลือกหมวดการเดินรถ
            = form_for @application, url: apply_applications_path, html: {id: 'form-apply'} do |f|
              = hidden_field_tag 'application[stage]', 'apply'
              %p
                %label
                  = f.radio_button :category, :category0 ,class: 'required'
                  %span= t(:category0, scope: 'qbus.application')
              %br
              %p
                %label
                  = f.radio_button :category, :category1 ,class: 'required'
                  %span= t(:category1, scope: 'qbus.application')
              %br
              %p
                %label
                  = f.radio_button :category, :category2 ,class: 'required'
                  %span= t(:category2, scope: 'qbus.application')
              %br
              %p
                %label
                  = f.radio_button :category, :category4 ,class: 'required'
                  %span= t(:category4, scope: 'qbus.application')
              %br
              %p
                %label
                  = f.radio_button :category, :category3 ,class: 'required'
                  %span= t(:category3, scope: 'qbus.application')
              %br
              .div.input-field#error-box{style: 'display: none;'}
                %ul#error-list
              %button.btn.waves-effect.waves-light.gradient-45deg-purple-deep-purple ไปยังขั้นตอนต่อไป

:javascript
  $("#form-apply").validate({
    messages: {
      category: 'โปรดระบุหมวดการเดินรถ'
    },
    errorContainer: '#error-box',
    errorLabelContainer: '#error-list',
    errorElement: 'div',
  });

app/views/applications/apply_step3.html.haml
.row
  .col.s12
    .card
      .card-content
        .card-title
          %h3 สมัครเข้าร่วมโครงการ Q-BUS
        .row
          .col.s12.m3
            = render "current_apply_step"
          .col.s12.m9
            %h4 ทำแบบประเมินตนเอง
            - if @application.extend
              .card-panel.light-blue.lighten-4
                ใบสมัครต่ออายุมาจากใบสมัครหมายเลข #{@application.extend_app&.id_text}
            ให้ผู้สมัครประเมินตนเองในหัวข้อต่อไปนี้ โดยให้ประเมินผลในแต่ละข้อให้ครบถ้วน

            %br
            %br
            .card-panel.gradient-45deg-light-green-amber
              %p{style: 'width: 80%'}
                ในการทำแบบประเมินตนเองของผู้สมัคร ผู้สมัครจะต้องทำแบบประเมินในแต่ละข้อให้ครบถ้วนและข้อมูลที่ประเมินต้องถูกต้องและตรงกับความเป็นจริงเท่านั้น เนื่องจากจะมีการตรวจประเมินหน้างานอีกครั้งตามขั้นตอนการตรวจประเมิน หากพบว่าข้อมูลที่ได้รับไม่ตรงกับความเป็นจริงในการตรวจประเมินหน้างาน จะถือว่าผู้สมัครมีความผิดร้ายแรง ผู้สมัครจะไม่ได้รับการพิจารณาจากกรรมการในการรับรองมาตรฐานรถโดยสารสาธารณะ Q-Bus
            %br
            = simple_form_for(@application, url: apply_step3_application_path(@application), method: 'post') do |f|
              %table
                %thead
                  %tr
                    %th{style: "width: 70%;"} หัวข้อ
                    %th{style: "width: 15%;"} ใช่
                    %th{style: "width: 15%;"} ไม่ใช่
                %tbody
                  - @application.self_evaluations.each do |ev|
                    %tr
                      %td= "#{ev.criterium.name}"
                      %td
                        %label
                          = radio_button_tag "result[#{ev.id}]", 'ok', ev.result == 1
                          %span ใช่
                      %td
                        %label
                          = radio_button_tag "result[#{ev.id}]", 'no', ev.result == 0
                          %span ไม่ใช่
              = hidden_field_tag 'application[stage]', 'step3'
              %br
              %button.btn.waves-effect.waves-light.gradient-45deg-purple-deep-purple ยืนยันใบสมัคร

app/views/applications/edit.html.haml
.row
  .col.s12
    .card
      .card-content
        .card-title= "แก้ไข#{t :application, scope: 'activerecord.models'}"
        = render partial: 'form', locals: {back_link: applications_path}

app/views/applications/extend.html.haml
.row
  .col.s12
    .card
      .card-content
        .card-title
          %h4 ต่ออายุใบสมัคร
        เลือกใบสมัครที่ต้องการต่ออายุจากรายการใบสมัครด้านล่างนี้ แล้วกดปุ่ม "ต่ออายุ" เพื่อทำการสร้างใบสมัครสำหรับการต่ออายุโดยใช้ข้อมูลเดิมที่ได้กรอกไว้แล้ว
      .card-content
        %table.dataTable
          %thead
            %tr
              %th หมายเลขใบสมัคร
              %th= t(:name, scope: 'activerecord.attributes.licensee')
              %th= t(:start, scope: 'activerecord.attributes.route')
              %th= t(:destination, scope: 'activerecord.attributes.route')
              %th วันที่ยื่นใบสมัคร
              %th วันที่หมดอายุ
              %th
          %tbody
            - @apps.each do |app|
              %tr
                %td= app.id
                %td= app.licensee&.name
                %td= app.route_start
                %td= app.route_destination
                %td= l(app.created_at, format: '%d %b %y')
                %td
                  = l(app.awarded_date + 1.year, format: '%d %b %y') if app.awarded_date
                %td
                  = link_to 'ต่ออายุ', extend_from_application_path(app), class: 'btn green waves-effect waves-light'

app/views/applications/index.html.haml
.row
  .col.s10.offset-s1
    .card
      .card-content.deep-purple
        .card-title
          %h4.white-text= @title
      .card-content
        .dataTables_wrapper
          %table#table.dataTable.display
            %thead
              %tr
                %th= t(:id, scope: 'activerecord.attributes.application')
                %th= t(:name, scope: 'activerecord.attributes.licensee')
                %th= t(:route_no, scope: 'activerecord.attributes.application')
                %th= t(:route_info, scope: 'activerecord.attributes.application')
                %th= t(:state, scope: 'activerecord.attributes.application')
                -#%th
            %tbody
              - @applications.each do |application|
                %tr
                  %td
                    %a{:href => application_path(application)}
                      = application.id_text
                  %td= application.licensee&.name
                  %td= application.route_no
                  %td= application.route_info
                  %td= application.state_text
                  -#%td.right-align
                  -#  %a{:href => application_path(application)}
                  -#    %i.material-icons pageview
                  -#  %a{:href => edit_application_path(application)}
                  -#    %i.material-icons edit
                  -#  %a{"href" => application_path(application), "rel" => "nofollow", "data-method" => "delete", "data-confirm" => t(:confirm_delete)}
                  -#    %i.material-icons delete
      -#.card-action
      -#  = link_to t(:new), apply_applications_path, class: 'btn green waves-effect waves-light'

:coffee
  $(document).ready ->
    $('#table').DataTable(
      $.extend(
        {
          #'responsive': true,
          'lengthChange': false,
          'columnDefs': [
            {'orderable': false, 'targets': -1},
            {'responsivePriority': 1, 'targets': 0},
            {'responsivePriority': 2, 'targets': -1}
          ]
        },
        dataTableDefaultOption()
      )
    )

app/views/applications/new.html.haml
.row
  .col.s12
    .container
      .card-panel
        %h3= "สร้าง#{t :application, scope: 'activerecord.models'}ใหม่"
        = render partial: 'form', locals: {back_link: applications_path}

%p

app/views/applications/show.html.haml
.row
  .col.s12
    .card.grey.darken-3
      .card-content
        %h5.white-text ข้อมูลใบสมัคร
      .card-tabs
        %ul.tabs.tabs-fixed-width.tabs-transparent.grey-text
          %li.tab
            %a.active{href: '#tab_app'}ข้อมูลใบสมัคร
          %li.tab
            %a{href: '#tab_evidence'}หลักฐาน
          %li.tab
            %a{href: '#tab_car'}ข้อมูลรถ
          %li.tab
            %a{href: '#tab_eval'}การประเมิน
          %li.tab
            %a{href: '#tab_visit'}การตรวจหน้างาน
          %li.tab
            %a{href: '#tab_award'}การตัดสินผล
      #tab_app
        .card-content.grey.lighten-5
          = render partial: "applications/application"
        .card-action.grey.lighten-3
          //= link_to 'แก้ไขข้อมูลใบสมัคร', apply_step1_application_path(@application), class: 'btn btn-green'
          = link_to 'ลบใบสมัคร', application_path(@application), method: 'delete', class: 'btn orange', data: {confirm: 'ต้องการลบใบสมัครออกจากระบบหรือไม่? คำเตือน: เมื่อลบแล้ว ข้อมูลทั้งหมดของใบสมัครนี้จะถูกลบ และจะไม่สามารถแก้ไขได้อีก' }
      #tab_eval
        .card-content.grey.lighten-5
          = render 'process/evaluation'
        .card-action.grey.lighten-3
          //= link_to 'แก้ไขข้อมูลการประเมิน', process_evaluation_path(@application), class: 'btn btn-green'
      #tab_car
        .card-content.grey.lighten-5
          = render partial: "applications/cars"
        .card-action.grey.lighten-3
          //= link_to 'แก้ไขข้อมูลรถ', apply_step2_application_path(@application,admin_edit:true), class: 'btn btn-green'
      #tab_evidence
        .card-content.grey.lighten-5
          %h4 รายการหลักฐาน
          = render "process/evidence"
        .card-action.grey.lighten-3
          //= link_to 'แก้ไขข้อมูลหลักฐาน', add_evidences_application_path(@application), class: 'btn btn-green'
      #tab_visit
        .card-content.grey.lighten-5
          %h4 ข้อมูลการตรวจประะเมินหน้างาน
          = render "process/visit"
        .card-action.grey.lighten-3
          //= link_to 'แก้ไขข้อมูลการตรวจหน้างาน', appointment_visit_path(@application), class: 'btn btn-green'
      #tab_award
        .card-content.grey.lighten-5
          .card-title
          .row
            .col.s6
              .row
                .col.s12
                  %h5 ผลการตัดสิน
                  - if @application.award_won
                    %span ได้มาตรฐาน  Q-BUS
                  - else
                    %span ไม่ผ่านมาตรฐาน  Q-BUS
              .section
              .row
                .col.s12
                  %h5 คำอธิบายผลการตัดสิน
                  = @application.award_remark
            .col.s6
              .row
                .col.s12
                  %h5 รายละเอียดคะแนน
              .row
                .col.s8.strong
                  คะแนนรวม
                .col.s4.right-align
                  = @application.total_score_text
              .row
                .col.s8.strong
                  คะแนนความปลอดภัย
                .col.s4.right-align
                  = @application.safety_score_text
              .row
                .col.s8.strong
                  การตรวจหน้างาน
                .col.s4.right-align
                  = @application.visit_summary_text
              .section
              .row
                .col.s8.strong
                  ผลที่ควรจะได้
                .col.s4.right-align
                  = @application.passed
        .card-action.grey.lighten-3
          //= link_to 'แก้ไขการตัดสินผล', process_award_path(@application), class: 'btn btn-green'