config/routes.rb
Rails.application.routes.draw do
  get 'report/award'
  resources :cars
  resources :routes
  resources :licensees
  resources :criteria
  resources :datafiles
  resources :attachments do
    member do
      get 'remove'
    end
  end
  resources :criteria_groups
  resources :violations
  resources :logs
  resources :public_comments, except: :edit do
    collection do
      get 'application/:application_id', to: 'public_comments#application'
    end
  end
  resources :announcements do
    member do
      get 'publish'
      delete 'main_attachment', to: 'announcements#delete_main_attachment', as: 'delete_main_attachment'
      delete 'other_attachments/:attachment_id', to: 'announcements#delete_other_attachments', as: 'delete_other_attachments'
    end
  end
  get 'public_announcement', to: 'announcements#lists'
  get 'add_comment', to: 'public_comments#add_comment'
  post 'add_comment', to: 'public_comments#add_comment_post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'static_pages/test1'

  resources :users
  get 'users/:id/edit_profile', to: 'users#edit_profile', as: 'profile_edit_user'
  patch 'users/:id/edit_profile', to: 'users#update_profile'


  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  #session
  get 'register', to: 'sessions#register'
  post 'register', to: 'sessions#register_post'
  get 'login(/:options)', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'profile', to: 'sessions#profile'

  resources :applications do
    member do
      get 'apply_step1'
      get 'apply_step2'
      get 'apply_step3'
      get 'fail_self_evaluation'
      post 'apply_step1', to: 'applications#post_step1'
      post 'apply_step2', to: 'applications#post_step2'
      post 'apply_step3', to: 'applications#post_step3'

      post 'add_car', to: 'applications#add_car'
      delete 'remove_car/:car_id', to: 'applications#remove_car', as: 'remove_car'

      get 'add_evidences'
      post 'add_attachment'
      get 'finish_add_evidences'
      get 'extend_from'
      get 'show_full'
    end
    collection do
      get 'apply'
      get 'extend'
      post 'apply', to: 'applications#post_apply'
      get 'dashboard'
      get 'finished'
      get 'in_progress'
    end
  end

  resources :evaluations

  #process
  get  'process/dashboard'

  get  'process/registers',       to: 'process#registered_index'
  get  'process/register/:id',    to: 'process#registered', as: 'process_register'
  post 'process/register/:id',    to: 'process#registered_post', as: 'confirm_process_register'

  get  'process/appointments',    to: 'process#appointment_index'
  get  'process/appointment_form'
  get  'process/appointment/visit/:id', to: 'process#appointment_visit', as: 'appointment_visit'
  post 'process/appointment/visit/:id', to: 'process#appointment_visit_post'
  post 'process/appointment',     to: 'process#appointment_post', as: 'appoint_process_appointment'
  get  'process/appointed/:id',   to: 'process#appointed', as: 'process_appointed'

  get  'process/verifications',   to: 'process#verification_index'
  get  'process/verification/:id',to: 'process#verification', as: 'process_verify'
  post 'process/verification/:id',to: 'process#verification_post'

  get  'process/evaluations',     to: 'process#evaluation_index'
  get  'process/evaluation/:id',  to: 'process#evaluation', as: 'process_evaluation'
  post 'process/evaluation/:id',  to: 'process#evaluation_post'
  post 'process/evaluation/:id/finish',  to: 'process#evaluation_finish', as: 'process_evaluation_finish'
  post 'process/evaluation/:id/reject',  to: 'process#evaluation_reject', as: 'process_evaluation_reject'

  get  'process/awards',          to: 'process#award_index'
  get  'process/award/:id',       to: 'process#award', as: 'process_award'
  post 'process/award/:id',       to: 'process#award_post'


end

app/controllers/process_controller.rb
class ProcessController < ApplicationController
  before_action :set_application, only: [ :registered, :registered_post,
                                          :appointment_post, :appointed, :appointment_visit, :appointment_visit_post,
                                          :evaluation, :evaluation_post, :evaluation_finish, :evaluation_reject,
                                          :award, :award_post,
                                        ]
  before_action :logged_in_user

  before_action only: [ :registered_index, :registered, :registered_post] do
    logged_in_with_role( [:verifier] )
  end

  before_action only: [ :appointment_index, :appointment_post, :appointed, :appointment_visit, :appointment_visit_post ] do
    logged_in_with_role( [:surveyor] )
  end

  before_action only: [ :evaluation_index, :evaluation, :evaluation_post, :evaluation_finish, :evaluation_reject] do
    logged_in_with_role( [:evaluator] )
  end

  before_action only: [ :award_index, :award, :award_post ] do
    logged_in_with_role( [:committee] )
  end

  before_action only: [
                        :registered, :registered_post,
                        :appointment_post, :appointed, :appointment_visit, :appointment_visit_post,
                        :evaluation, :evaluation_post, :evaluation_finish, :evaluation_reject,
                        :award, :award_post,
                      ] do
    can_access_app_by_province(@application)
  end

  def dashboard
    #for licensee
    @applying = Application.on_applying(@current_user)
    @need_evidences = Application.need_evidence(@current_user)
    @finished = Application.finished(@current_user)
    @waiting_official = Application.waiting_official(@current_user)

    #for officer & admin
    if @current_user.can_view_all_provinces?
      @to_be_confirmed = Application.to_be_confirmed
      @to_be_appointed = Application.to_be_appointed
      @to_be_appointed_filled = Application.to_be_appointed_filled
      @to_be_visited = Application.to_be_visited
      @to_be_evaluated = Application.to_be_evaluated
      @to_be_awarded = Application.to_be_awarded
    else
      @to_be_confirmed = Application.to_be_confirmed.where('license_no LIKE ?',"#{@current_user.province}%")
      @to_be_appointed = Application.to_be_appointed.where('license_no LIKE ?',"#{@current_user.province}%")
      @to_be_appointed_filled = Application.to_be_appointed_filled.where('license_no LIKE ?',"#{@current_user.province}%")
      @to_be_visited = Application.to_be_visited.where('license_no LIKE ?',"#{@current_user.province}%")
      @to_be_evaluated = Application.to_be_evaluated.where('license_no LIKE ?',"#{@current_user.province}%")
      @to_be_awarded = Application.to_be_awarded.where('license_no LIKE ?',"#{@current_user.province}%")
    end
  end

  #-------- verifier -----------------
  def registered_index
    if @current_user.can_view_all_provinces?
      @to_be_confirmed = Application.to_be_confirmed
      @latest_confirmed = Application.latest_confirmed
    else
      @to_be_confirmed = Application.to_be_confirmed.where('license_no LIKE ?',"#{@current_user.province}%")
      @latest_confirmed = Application.latest_confirmed.where('license_no LIKE ?',"#{@current_user.province}%")
    end
  end

  def registered

  end

  def registered_post
    if params[:result] == 'ok'
      @application.confirm_result = true
      @application.confirm_comment = "ใบสมัครถูกต้อง"
      @application.confirm_registration
    elsif params[:result] == 'no'
      comment = params[:confirm_comment].strip
      if comment.blank?
        redirect_to process_register_path(@application), flash: {error: "ในกรณีที่ไม่ผ่านการตรวจ จะต้องระบุคำอธิบาย"}
        return
      else
        @application.confirm_result = false
        @application.confirm_comment = "#{params[:confirm_comment]}"
        @application.reject_registration
      end
    else
      redirect_to process_register_path(@application), flash: {error: "โปรดระบุผลการตรวจ"}
      return
    end
    redirect_to process_registers_path, notice: "บันทึกผลการตรวจใบสมัครหมายเลข #{@application.id_text} เรียบร้อย"
  end


  #-------- surveyor -----------------
  def appointment_index
    if @current_user.can_view_all_provinces?
      @to_be_appointed = Application.to_be_appointed
      @to_be_appointed_filled = Application.to_be_appointed_filled
      @to_be_visited = Application.to_be_visited
      @latest_visited = Application.latest_visited
    else
      @to_be_appointed = Application.to_be_appointed.where('license_no LIKE ?',"#{@current_user.province}%")
      @to_be_appointed_filled = Application.to_be_appointed_filled.where('license_no LIKE ?',"#{@current_user.province}%")
      @to_be_visited = Application.to_be_visited.where('license_no LIKE ?',"#{@current_user.province}%")
      @latest_visited = Application.latest_visited.where('license_no LIKE ?',"#{@current_user.province}%")
    end
  end

  def appointment_post
    @application.appointment_date = params[:appointment_date]
    @application.appointment_remark = params[:appointment_remark]
    @application.save
    redirect_to process_appointments_path
  end

  def appointed
    redirect_to process_appointments_path
  end

  def appointment_visit
    @application.add_missing_evaluation
  end

  def appointment_visit_post
    #save applications param
    @application.update(application_visit_params)

    #save evaluations
    ev_result = application_evaluation_params
    @application.evaluations.each do |ev|
      if ev_result[ev.id.to_s] == '1'
        ev.result = 1
      elsif ev_result[ev.id.to_s] == '0.5'
        ev.result = 0.5
      elsif ev_result[ev.id.to_s] == '0'
        ev.result = 0
      end
      ev.save
    end

    if params[:confirm]
      if @application.evaluation_visit_all_evaluated
        @application.visited = true
        @application.visited_confirm_date = Time.zone.now
      else
        @application.save
        redirect_to appointment_visit_path(@application), flash: {notice: 'บันทึกผลการตรวจหน้างานเรียบร้อย', error: 'ไม่สามารถยืนยันการตรวจหน้างานได้ เนื่องจากยังประเมินไม่ครบทุกรายการ' }
        return
      end
    end

    @application.save

    if params[:confirm]
      redirect_to process_appointments_path, notice: 'ยืนยันผลการตรวจหน้างานเรียบร้อย'
    else
      redirect_to appointment_visit_path(@application), notice: 'บันทึกผลการตรวจหน้างานเรียบร้อย'
    end
  end

  #-------- evaluator -----------------
  def evaluation_index

    if @current_user.can_view_all_provinces?
      @to_be_evaluated = Application.to_be_evaluated
      @latest_evaluated = Application.latest_evaluated
    else
      @to_be_evaluated = Application.to_be_evaluated.where('license_no LIKE ?',"#{@current_user.province}%")
      @latest_evaluated = Application.latest_evaluated.where('license_no LIKE ?',"#{@current_user.province}%")
    end
  end

  def evaluation
    @application.add_missing_evaluation
  end

  def evaluation_post
    #save evaluations
    ev_result = application_evaluation_params
    @application.evaluation_main.each do |ev|
      if ['1','0.67','0.5', '0.33', '0'].include? ev_result[ev.id.to_s]
        ev.result = ev_result[ev.id.to_s].to_f
      end
      ev.description = params.require(:description)[ev.id.to_s]
      ev.save
    end

    if params[:confirm]
      if @application.evaluated_count < Criterium.need_evaluation.count
        redirect_to process_evaluation_path(@application), flash: {error: 'ยังประเมินไม่ครบทุกหัวข้อ'}
      else
        @application.evaluation_finish
        redirect_to process_evaluations_path, notice: 'ยืนยันผลการประเมินเรียบร้อย'
      end
    else
      redirect_to process_evaluation_path(@application), notice: 'บันทึกผลการประเมินเรียบร้อย'
    end
  end

  def evaluation_finish
  end

  def evaluation_reject
    @application.reject_evidence(params[:evaluation_result])
    redirect_to process_evaluations_path
  end

  #--------------- committee ---------------------------
  def award_index
    if @current_user.can_view_all_provinces?
      @to_be_awarded = Application.to_be_awarded
      @awarded_recent = Application.latest_awarded
    else
      @to_be_awarded = Application.to_be_awarded.where('license_no LIKE ?',"#{@current_user.province}%")
      @awarded_recent = Application.latest_awarded.where('license_no LIKE ?',"#{@current_user.province}%")
    end
  end

  def award
  end

  def award_post
    if params[:result] == 'ok'
      @application.award = 'ได้รับตราสัญลักษณ์'
      @application.award_won = true
      @application.award_expire_date = Time.zone.now + 3.year
    elsif params[:result] == 'no'
      @application.award = 'ไม่ได้รับตราสัญลักษณ์'
      @application.award_won = false
      @application.award_remark = params[:award_remark]
    else
    end
    @application.set_award
    redirect_to process_awards_path, notice: "บันทึกการตัดสินผลเรียบร้อย"
  end

  private
    def set_application
      @application = Application.find(params[:id])
    end

    def application_visit_params
      params.require(:application).permit(:visited_date, :visitor, :visitor_tel, :visitor_email, :visitor_position,
                                          :visit_comment, :visit_problem, :visit_problem_cause, :visit_result, :visit_tax_89, :visit_tax_accrued,
                                          :visit_car1_chassis,:visit_car1_light,:visit_car1_tire,:visit_car1_windshield,
                                          :visit_car2_chassis,:visit_car2_light,:visit_car2_tire,:visit_car2_windshield,
                                          :visit_car3_chassis,:visit_car3_light,:visit_car3_tire,:visit_car3_windshield,
                                          :visit_car4_chassis,:visit_car4_light,:visit_car4_tire,:visit_car4_windshield)

    end

    def application_evaluation_params
      params.fetch(:result, {})
    end
end

app/helpers/process_helper.rb
module ProcessHelper
end

app/views/process/_evaluation.html.haml
- last_cg = nil
- @application.evaluations.joins(:criterium => :criteria_group).order('criteria_groups.id, criteria.id').each do |ev|
  - if ev.criterium.criteria_group != last_cg
    - last_cg = ev.criterium.criteria_group
    .divider
    .row
      .col.s12
        %h5= last_cg.name
    .row
      .col.s7
        = t(:name, scope: 'activerecord.attributes.criterium')
      .col.s2.center
        ผลการประเมิน
      .col.s3
        คำอธิบายผลการประเมิน
  .row
    .col.s7
      = "#{ev.criterium.number}. #{ev.criterium.name}"
      %br
      - if ev.is_main_evaluation?
        .row
          .col.s2
          .col.s7.strong หลักฐานที่แนบมาด้วย
          .col.s3
        - ev.criterium.evidences.each do |evid|
          .row
            .col.s2
            .col.s7
              = evid.name
            .col.s3
              - att = @application.attachments.where(evidence: evid)
              - if att.count > 0
                = link_to rails_blob_path(att.first.data, disposition: "attachment") do
                  %i.material-icons.small insert_drive_file
                  = t(:download)
              - else
                %span.red-text - ไม่ได้แนบ -
        %br
    .col.s2.center
      - if ev.result == 1
        %i.material-icons.left check
        100%
      - elsif ev.result == 0
        %i.material-icons.left block
        0%
      - else
        %i.material-icons.left remove
        50%
    .col.s3
      .input-field
        /= f.text_field :description
        = ev.description

app/views/process/_evidence.html.haml
- cgroups = CriteriaGroup.need_evidence unless cgroups
- enable_delete = false unless enable_delete
%table
  %thead
    %tr
      %th ข้อ
      %th ชื่อหลักฐาน
      %th วัน/เวลา ยื่นเอการ
      %th
      - if enable_delete
        %th
  %tbody
    - cgroups.each do |cg|
      - cg.criterium.each do |ci|
        - ci.evidences.each do |ev|
          %tr
            %td{style: 'vertical-align: top'}= ci.number_text
            %td{style: 'vertical-align: top'}= ev.name
            - att = @application.attachments.where(evidence: ev)
            %td{style: 'vertical-align: top'}
              - if att.count > 0
                = l(ev.created_at,format: :short_date)
              - else
                %span.red-text - ยังไม่ได้แนบ -
            %td{style: 'vertical-align: top'}
              - if att.count > 0
                = link_to rails_blob_path(att.first.data, disposition: "attachment") do
                  %i.material-icons.small insert_drive_file
                  = att.first.data.filename
            - if enable_delete
              %td
                - if att.count > 0
                  = link_to 'ลบ', remove_attachment_path(att.first), data: {confirm: "ต้องการลบหลักฐาน \"#{att.first.data.filename}\" หรือไม่?"}

app/views/process/appointment_post.html.haml
%h1 Process#appointment_post
%p Find me in app/views/process/appointment_post.html.haml

app/views/process/award_index.html.haml
.row
  .col.s12
    .card.gradient-45deg-light-green-amber
      .card-content
        .card-title
          %h5 การบันทึกผลการให้ตราสัญลักษณ์
        %p ให้พิจารณาผลการประเมินของใบสมัคร โดยให้กดปุ่ม "ตัดสินผล" เพื่อดูข้อมูลใบสมัครโดยละเอียดและทำการบันทึกผลการตัดสิน
        %br
        %p ระบบจะแนะนำผลการให้รางวัล โดยคำนวณจากเกณฑ์คือ คะแนนต้องไม่น้อยกว่า 80 และ คะแนนความปลอดภัยต้องไม่น้อยกว่า 25 โดยที่ต้องผ่านการประเมินตนเองทั้งหมดและผ่านการตรวจหน้างา่นทุกรายการ
    .card
      .card-content
        .row
          .col.s12
            %h4 ใบสมัครรอการตัดสินผล
            %table
              %thead
                %tr
                  %th หมายเลข
                  %th= t(:name, scope: 'activerecord.attributes.licensee')
                  %th= t(:route_no, scope: 'activerecord.attributes.application')
                  %th= t(:route_info, scope: 'activerecord.attributes.application')
                  %th วันที่ยื่นใบสมัคร
                  %th.right-align คะแนนรวม
                  %th.right-align คะแนนความปลอดภัย
                  %th แนะนำผล
                  %th
              %tbody
                - @to_be_awarded.each do |app|
                  %tr
                    %td= app.id_text
                    %td= app.licensee.name
                    %td= app.route_no
                    %td= app.route_info
                    %td= thai_year(app.created_at, '%d %b tYY')
                    %td.right-align= "#{app.total_score}/100"
                    %td.right-align= "#{app.safety_score}/30"
                    %td= app.passed
                    %td= link_to 'ตัดสินผล', process_award_path(app.id), class: 'waves-effect waves-light btn gradient-45deg-deep-orange-orange'
    .card
      .card-content
        .row
          .col.s12
            %h4 ใบสมัครล่าสุดที่ตัดสินผลแล้ว (ภายใน 30 วันที่ผ่านมา)
            %table
              %thead
                %tr
                  %th หมายเลข
                  %th= t(:name, scope: 'activerecord.attributes.licensee')
                  %th= t(:route_no, scope: 'activerecord.attributes.application')
                  %th= t(:route_info, scope: 'activerecord.attributes.application')
                  %th วันที่ยื่นใบสมัคร
                  %th คะแนนรวม
                  %th= t(:awarded_date, scope: 'activerecord.attributes.application')
                  %th ผลการตัดสิน
                  %th
              %tbody
                - @awarded_recent.each do |app|
                  %tr
                    %td= app.id_text
                    %td= app.licensee.name
                    %td= app.route_no
                    %td= app.route_info
                    %td= thai_year(app.created_at, '%d %b tYY')
                    %td= app.total_score
                    %td= thai_year(app.awarded_date, '%d %b tYY')
                    %td= final_award_text(app)
                    %td
                      - if @current_user.is_admin?
                        = link_to 'แก้ไขผล', process_award_path(app.id), class: 'waves-effect waves-light btn gradient-45deg-deep-orange-orange'

app/views/process/dashboard.html.haml
.row
  .col.s12
    - if @current_user&.has_role(:licensee)
      .row
        .col.s12.m12
          .card
            .card-content
              %h5 ใบสมัครรอการดำเนินการโดยผู้ประกอบการ
              ใบสมัครต่อไปนี้ยังมีขั้นตอนที่ต้องดำเนินการโดยผู้ประกอบการ ขอให้ดำเนินการให้ครบถ้วน
            .divider
            .card-content.grey.lighten-4
              %h6 ใบสมัครอยู่ระหว่างกรอกข้อมูลเบื้องต้น
              - if @applying.count > 0
                %table
                  %thead
                    %tr
                      %th หมายเลข
                      %th= t(:name, scope: 'activerecord.attributes.licensee')
                      %th= t(:route_no, scope: 'activerecord.attributes.application')
                      %th= t(:route_info, scope: 'activerecord.attributes.application')
                      %th วันที่ยื่นใบสมัคร
                      %th= t(:state, scope: 'activerecord.attributes.application')
                      %th
                  %tbody
                    - @applying.each do |app|
                      %tr
                        %td= app.id_text
                        %td= app.licensee&.name
                        %td= app.route_no
                        %td= app.route_info
                        %td= thai_year(app.created_at, '%d %b tYY')
                        %td
                          = state_full(app)
                          - if app.confirm_result == false
                            %p.red-text.tooltipped{data: {tooltip: app.confirm_comment, position: 'bottom'}}
                              %i.material-icons.left error
                              ใบสมัครไม่ถูกต้อง
                        %td.strong
                          = link_to 'แก้ไข', apply_step1_application_path(app)
                          /= link_to 'แก้ไข', apply_step1_application_path(app), class: 'button waves-effect waves-light blue darken-2 btn'
              - else
                ไม่มีใบสมัครอยู่ระหว่างการกรอกข้อมูลเบื้องต้น

            .divider
            .card-content.grey.lighten-3
              %h6 ใบสมัครรอการส่งหลักฐานเพิ่มเติม
              - if @need_evidences.count > 0
                %table
                  %thead
                    %tr
                      %th หมายเลข
                      %th= t(:name, scope: 'activerecord.attributes.licensee')
                      %th= t(:route_no, scope: 'activerecord.attributes.application')
                      %th= t(:route_info, scope: 'activerecord.attributes.application')
                      %th วันที่ยื่นใบสมัคร
                      %th การตรวจหน้างาน
                      %th= t(:state, scope: 'activerecord.attributes.application')
                      %th
                  %tbody
                    - @need_evidences.each do |app|
                      %tr
                        %td= app.id_text
                        %td= app.licensee&.name
                        %td= app.route_no
                        %td= app.route_info
                        %td= thai_year(app.created_at, '%d %b tYY')
                        %td= app.visit_status
                        %td
                          = state_full(app)
                          - if app.evaluation_result.blank? == false && app.evaluated_date
                            %p.red-text.tooltipped{data: {tooltip: app.evaluation_result, position: 'bottom'}}
                              %i.material-icons.left error
                              หลักฐานมีปัญหา
                        %td.strong
                          = link_to 'ส่งหลักฐาน', add_evidences_application_path(app)
              - else
                ไม่มีใบสมัครที่ต้องส่งหลักฐานเพิ่มเติม
            .card-action
              = link_to 'สร้างใบสมัครใหม่', apply_applications_path, class: 'btn waves-effect waves-light green'
              = link_to 'กลับไปหน้าแรก', root_path, class: 'btn waves-effect waves-light gradient-45deg-deep-orange-orange'
          .card
            .card-content
              %h5 ใบสมัครรอดำเนินการโดยเจ้าหน้าที่
              - if @waiting_official.count > 0
                ใบสมัครต่อไปนี้อยู่ระหว่างการตรวจสอบข้อมูลหรือหลักฐานต่าง ๆ โดยกรมการขนส่งทางบก ขอให้ผู้ใช้รอผล
                %table
                  %thead
                    %tr
                      %th หมายเลข
                      %th= t(:name, scope: 'activerecord.attributes.licensee')
                      %th= t(:route_no, scope: 'activerecord.attributes.application')
                      %th= t(:route_info, scope: 'activerecord.attributes.application')
                      %th วันที่ยื่นใบสมัคร
                      %th การตรวจหน้างาน
                      %th= t(:state, scope: 'activerecord.attributes.application')
                  %tbody
                    - @waiting_official.each do |app|
                      %tr
                        %td= app.id_text
                        %td= app.licensee&.name
                        %td= app.route_no
                        %td= app.route_info
                        /%td= l(app.created_at, format: :short_date, default: nil)
                        %td= thai_year(app.created_at, '%d %B tYY')
                        %td= app.visit_status
                        %td= state_full(app)
              - else
                ไม่มีใบสมัครรอการตรวจสอบ

          .card
            .card-content
              %h5 ใบสมัครดำเนินการเสร็จแล้ว
              - if @finished.count > 0
                ใบสมัครต่อไปนี้ดำเนินการเสร็จสิ้นแล้ว สามารถตรวจดูผลการดำเนินการได้ด้านล่างนี้
                %table
                  %thead
                    %tr
                      %th หมายเลข
                      %th ผู้ประกอบการ
                      %th= t(:route_no, scope: 'activerecord.attributes.application')
                      %th= t(:route_info, scope: 'activerecord.attributes.application')
                      %th ยื่นใบสมัคร
                      %th ตัดสินผล
                      %th ผลการตัดสิน
                      %th หมดอายุ
                      %th
                  %tbody
                    - @finished.each do |app|
                      %tr
                        %td= app.id_text
                        %td= app.licensee&.name
                        %td= app.route_no
                        %td= app.route_info
                        %td= thai_year(app.created_at, '%d %b tYY')
                        -# %td= l(app.created_at, format: :short_date, default: nil)
                        %td= thai_year(app.awarded_date, '%d %b tYY')
                        -# %td= l(app.awarded_date, format: :short_date, default: nil)
                        %td= final_award_text(app)
                        %td= thai_year(app.award_expire_date, '%d %b tYY')
                        -# %td= l(app.award_expire_date, format: :short_date, default: nil)
                        %td
                          - if app.award_won
                            / = link_to 'ต่ออายุ', extend_from_application_path(app), class: 'btn green waves-effect waves-light'
                            %button.waves-effect.waves-light.green.modal-trigger.btn{ data: {target: 'extend-app',url: extend_from_application_url(app)}} ต่ออายุ
              - else
                ไม่มีใบสมัครที่ดำเนินการเสร็จแล้ว
    - if @current_user&.is_official?
      .row
        .col.s12.m12
          .card
            .card-content
              .card-title
                %h5 ใบสมัครรอการดำเนินการโดยเจ้าหน้าที่กรมการขนส่งทางบก
            - if @current_user.has_role(:verifier)
              .divider
              .card-content
                .card-title
                  %h6 ระบบงานตรวจสอบใบสมัคร
                .row
                  .col.s8
                    มีใบสมัครจำนวน #{@to_be_confirmed.count} ใบที่รอการตรวจสอบ
                  .col.s4.right-align
                    = link_to 'ตรวจสอบ', process_registers_path, class: 'btn btn-small gradient-45deg-deep-orange-orange'
            - if @current_user.has_role(:evaluator)
              .divider
              .card-content
                .card-title
                  %h6 ระบบประเมินผล
                .row
                  .col.s8
                    มีใบสมัครจำนวน #{@to_be_evaluated.count} ใบที่รอการประเมิน
                  .col.s4.right-align
                    = link_to 'ประเมิน', process_evaluations_path, class: 'btn btn-small gradient-45deg-deep-orange-orange'
            - if @current_user.has_role(:surveyor)
              .divider
              .card-content
                .card-title
                  %h6 ระบบงานนัดหมาย และ ตรวจหน้างาน
                .row
                  .col.s8
                    มีใบสมัครจำนวน #{@to_be_appointed.count} ใบที่รอการนัดหมาย
                    %br
                    มีใบสมัครจำนวน #{@to_be_visited.count} ใบที่รอการตรวจหน้างาน
                  .col.s4.right-align
                    = link_to 'นัดหมาย', process_appointments_path, class: 'btn btn-small gradient-45deg-deep-orange-orange'
            - if @current_user.has_role(:committee)
              .divider
              .card-content
                .card-title
                  %h6 ระบบตัดสินผลมาตรฐาน
                .row
                  .col.s8
                    มีใบสมัครจำนวน #{@to_be_awarded.count} ใบที่รอการตัดสินผลมาตรฐานตราสัญลักษณ์ Q-BUS
                  .col.s4.right-align
                    = link_to 'ตัดสินผล', process_awards_path, class: 'btn gradient-45deg-deep-orange-orange btn-small'

= render "applications/extend_modal"