config/routes.rb
Rails.application.routes.draw do
  get 'report/award'
  resources :cars
  resources :routes
  resources :licensees
  resources :criteria
  resources :datafiles
  resources :attachments do
    member do
      get 'remove'
    end
  end
  resources :criteria_groups
  resources :violations
  resources :logs
  resources :public_comments, except: :edit do
    collection do
      get 'application/:application_id', to: 'public_comments#application'
    end
  end
  resources :announcements do
    member do
      get 'publish'
      delete 'main_attachment', to: 'announcements#delete_main_attachment', as: 'delete_main_attachment'
      delete 'other_attachments/:attachment_id', to: 'announcements#delete_other_attachments', as: 'delete_other_attachments'
    end
  end
  get 'public_announcement', to: 'announcements#lists'
  get 'add_comment', to: 'public_comments#add_comment'
  post 'add_comment', to: 'public_comments#add_comment_post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'static_pages/test1'

  resources :users
  get 'users/:id/edit_profile', to: 'users#edit_profile', as: 'profile_edit_user'
  patch 'users/:id/edit_profile', to: 'users#update_profile'


  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  #session
  get 'register', to: 'sessions#register'
  post 'register', to: 'sessions#register_post'
  get 'login(/:options)', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'profile', to: 'sessions#profile'

  resources :applications do
    member do
      get 'apply_step1'
      get 'apply_step2'
      get 'apply_step3'
      get 'fail_self_evaluation'
      post 'apply_step1', to: 'applications#post_step1'
      post 'apply_step2', to: 'applications#post_step2'
      post 'apply_step3', to: 'applications#post_step3'

      post 'add_car', to: 'applications#add_car'
      delete 'remove_car/:car_id', to: 'applications#remove_car', as: 'remove_car'

      get 'add_evidences'
      post 'add_attachment'
      get 'finish_add_evidences'
      get 'extend_from'
      get 'show_full'
    end
    collection do
      get 'apply'
      get 'extend'
      post 'apply', to: 'applications#post_apply'
      get 'dashboard'
      get 'finished'
      get 'in_progress'
    end
  end

  resources :evaluations

  #process
  get  'process/dashboard'

  get  'process/registers',       to: 'process#registered_index'
  get  'process/register/:id',    to: 'process#registered', as: 'process_register'
  post 'process/register/:id',    to: 'process#registered_post', as: 'confirm_process_register'

  get  'process/appointments',    to: 'process#appointment_index'
  get  'process/appointment_form'
  get  'process/appointment/visit/:id', to: 'process#appointment_visit', as: 'appointment_visit'
  post 'process/appointment/visit/:id', to: 'process#appointment_visit_post'
  post 'process/appointment',     to: 'process#appointment_post', as: 'appoint_process_appointment'
  get  'process/appointed/:id',   to: 'process#appointed', as: 'process_appointed'

  get  'process/verifications',   to: 'process#verification_index'
  get  'process/verification/:id',to: 'process#verification', as: 'process_verify'
  post 'process/verification/:id',to: 'process#verification_post'

  get  'process/evaluations',     to: 'process#evaluation_index'
  get  'process/evaluation/:id',  to: 'process#evaluation', as: 'process_evaluation'
  post 'process/evaluation/:id',  to: 'process#evaluation_post'
  post 'process/evaluation/:id/finish',  to: 'process#evaluation_finish', as: 'process_evaluation_finish'
  post 'process/evaluation/:id/reject',  to: 'process#evaluation_reject', as: 'process_evaluation_reject'

  get  'process/awards',          to: 'process#award_index'
  get  'process/award/:id',       to: 'process#award', as: 'process_award'
  post 'process/award/:id',       to: 'process#award_post'


end

app/models/public_comment.rb
class PublicComment < ApplicationRecord
  belongs_to :route, optional: true
  belongs_to :car, optional: true
  belongs_to :licensee, optional: true

  validates :comment, presence: true
  validates :commenter_name, presence: true
  validates :commenter_contact, presence: true
  validates :commenter_address, presence: true

  before_validation :update_references

  def self.by_application(application_id)
    comments = PublicComment.none

    curApp = Application.find(application_id)
    if (curApp == nil)
      return comments
    end

    rid = curApp.route_id
    lid = curApp.licensee_id
    cids = curApp.cars&.pluck(:id)

    if (rid != nil)
      comments = comments.or(PublicComment.where(route_id: rid))
    end

    if (lid != nil)
      comments = comments.or(PublicComment.where(licensee_id: lid))
    end

    if (!cids.empty?)
      comments = comments.or(PublicComment.where(car_id: cids))
    end

    return comments
  end

  def to_label
    "[#{self.updated_at}] #{self.commenter_name}"
  end

  # update reference based on user input. reference should be <nil> if not found
  def update_references
    self.route = Route.where(route_no: self.route_no).first()
    self.car = Car.where(plate: self.car_plate).first()
    self.licensee = Licensee.where(name: self.licensee_name).first()
  end
end

app/controllers/public_comments_controller.rb
class PublicCommentsController < ApplicationController
  before_action :set_public_comment, only: [:show, :edit, :update, :destroy]

  # GET /public_comments
  # GET /public_comments.json
  def index
    @public_comments = PublicComment.all
  end

  # GET /public_comments/1
  # GET /public_comments/1.json
  def show
  end

  def application
    @public_comments = PublicComment.by_application(params[:application_id])
  end

  # GET /public_comments/new
  def new
    @public_comment = PublicComment.new
  end

  def add_comment
    @public_comment = PublicComment.new
  end

  def add_comment_post
    puts public_comment_params
    @public_comment = PublicComment.new(public_comment_params)

    if @public_comment.save
      redirect_to root_path, notice: 'ข้อคิดเห็นของท่านไ้ดรับการบันทึกเรียบร้อยแล้ว'
    else
      render :add_comment
    end
  end


  # POST /public_comments
  # POST /public_comments.json
  def create
    puts public_comment_params
    @public_comment = PublicComment.new(public_comment_params)

    respond_to do |format|
      if @public_comment.save
        format.html { redirect_to @public_comment, notice: 'Public comment was successfully created.' }
        format.json { render :show, status: :created, location: @public_comment }
      else
        format.html { render :new }
        format.json { render json: @public_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /public_comments/1
  # PATCH/PUT /public_comments/1.json
  def update
    respond_to do |format|
      if @public_comment.update(public_comment_params)
        format.html { redirect_to @public_comment, notice: 'Public comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @public_comment }
      else
        format.html { render :edit }
        format.json { render json: @public_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /public_comments/1
  # DELETE /public_comments/1.json
  def destroy
    @public_comment.destroy
    respond_to do |format|
      format.html { redirect_to public_comments_url, notice: 'Public comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_public_comment
      @public_comment = PublicComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def public_comment_params
      params.require(:public_comment).permit(:route_no, :route_id, :car_plate, :car_id, :licensee_name, :licensee_id, :comment, :commenter_name, :commenter_contact, :commenter_address)
    end
end

app/helpers/public_comments_helper.rb
module PublicCommentsHelper
end

app/views/public_comments/_comment.html.haml
.row
  .col.s10.offset-s1
    .card
      .card-content.deep-purple
        .card-title
          %h4.white-text= t(:list) + t(:public_comment, scope: 'activerecord.models')
      .card-content
        .dataTables_wrapper
          %table#table.dataTable.display
            %thead
              %tr
                %th= t(:route_no, scope: 'activerecord.attributes.public_comment')
                %th= t(:car_plate, scope: 'activerecord.attributes.public_comment')
                %th= t(:licensee_name, scope: 'activerecord.attributes.public_comment')
                %th= t(:created_at)
                %th
            %tbody
              - @public_comments.each do |public_comment|
                %tr
                  %td= public_comment.route_no
                  %td= public_comment.car_plate
                  %td= public_comment.licensee_name
                  %td= l(public_comment.created_at, format: :short_date, default: nil)
                  %td.right-align
                    %a{:href => public_comment_path(public_comment)}
                      %i.material-icons pageview
                    /%a{:href => edit_public_comment_path(public_comment)}
                    /  %i.material-icons edit
                    %a{"href" => public_comment_path(public_comment), "rel" => "nofollow", "data-method" => "delete", "data-confirm" => t(:confirm_delete)}
                      %i.material-icons delete
      .card-action
        = link_to t(:new), new_public_comment_path, class: 'btn green waves-effect waves-light'

:coffee
  $(document).ready ->
    $('#table').DataTable(
      $.extend(
        {
          'responsive': true,
          'lengthChange': false,
          'columnDefs': [
            {'orderable': false, 'targets':-1},
            {'responsivePriority': 1, 'targets': 0},
            {'responsivePriority': 2, 'targets': -1}
          ]
        },
        dataTableDefaultOption()
      )
    )

app/views/public_comments/_form.html.haml
= simple_form_for(@public_comment, url: form_url,  method: form_method) do |f|
  = f.error_notification
  .row
    .col.s12
      .row
        .input-field.col.s12
          %i.material-icons.prefix airport_shuttle
          = f.input_field :route_no, list: 'route_list'
          %datalist{id: 'route_list'}
            - Route.all.each do |route|
              %option{value: route.route_no}
          = f.label :route_no
          = f.full_error :route_no
        .input-field.col.s12
          %i.material-icons.prefix directions_car
          = f.input_field :car_plate, list: 'car_list'
          %datalist{id: 'car_list'}
            - Car.all.each do |car|
              %option{value: car.plate}
          = f.label :car_plate
          = f.full_error :car_plate
        .input-field.col.s12
          %i.material-icons.prefix help
          = f.input_field :licensee_name, list: 'licensee_list'
          %datalist{id: 'licensee_list'}
            - Licensee.all.each do |licensee|
              %option{value: licensee.name}
          = f.label :licensee_name
          = f.full_error :licensee_name
        .input-field.col.s12
          %i.material-icons.prefix chat
          = f.input_field :comment, class: 'materialize-textarea', style: 'height: 70px;'
          = f.label :comment
          = f.full_error :comment
        .input-field.col.s12
          %i.material-icons.prefix person
          = f.input_field :commenter_name
          = f.label :commenter_name
          = f.full_error :commenter_name
        .input-field.col.s12
          %i.material-icons.prefix contact_phone
          = f.input_field :commenter_contact
          = f.label :commenter_contact
          = f.full_error :commenter_contact
        .input-field.col.s12
          %i.material-icons.prefix contact_mail
          = f.input_field :commenter_address
          = f.label :commenter_address
          = f.full_error :commenter_address
  %button.btn.waves-effect.waves-light.left.gradient-45deg-purple-deep-purple ส่งข้อคิดเห็น
- if back_link
  = link_to t(:cancel), back_link, style: "margin-left: 2em", class: "btn-flat dlp-purple-text strong waves-black waves-effect"

app/views/public_comments/add_comment.html.haml
.row
  .col.s12.m4.push-m8
    .card.gradient-45deg-light-green-amber
      .card-content
        %p{style: 'padding-bottom: 1rem;'}
          ผู้ใช้บริการรถโดยสารสาธารณะสามารถให้ข้อคิดเห็นแนะนำติชมต่อรถต่าง ๆ ที่ใช้งานได้ โดยกรอกข้อมูลในแบบฟอร์มนี้ และกดปุ่ม "ส่งความคิดเห็น" เมื่อกรอกข้อมเรียบร้อยแล้ว
        %p{style: 'padding-bottom: 1rem;'}
          กรุณาระบุชื่อ - ที่อยู่ และหมายเลขโทรศัพท์สำหรับติดต่อกลับ

  .col.s12.m8.pull-m4
    .card
      .card-content.deep-purple
        .card-title.white-text
          %h4.white-text= 'ส่งข้อคิดเห็น'
      .card-content
        = render partial: 'form', locals: {back_link: root_path, form_url: add_comment_path, form_method: :post}

app/views/public_comments/application.html.haml
= render partial: 'comment'

app/views/public_comments/edit.html.haml
.row
  .col.s6.offset-s3
    .card
      .card-content.deep-purple
        .card-title
          %h1.white-text= t(:edit) + t(:public_comment, scope: 'activerecord.models')
      .card-content
        = render partial: 'form', locals: {back_link: public_comments_path, form_url: public_comment_path(@public_comment), form_method: :patch}

app/views/public_comments/index.html.haml
.row
  .col.s6.offset-s3
    .card
      .card-content.deep-purple
        .card-title.white-text
          %h1= t(:list) + t(:public_comment, scope: 'activerecord.models')
      .card-content
        %ul.collection
          - @public_comments.each do |public_comment|
            %li.collection-item.avatar
              %i.material-icons.circle comment
              %span.title="#{public_comment.to_label}"
              %p
                ="#{t(:route_no, scope: 'activerecord.attributes.public_comment')} #{public_comment.route_no}"
                %br
                ="#{t(:car_plate, scope: 'activerecord.attributes.public_comment')} #{public_comment.car_plate}"
                %br
                ="#{t(:licensee_name, scope: 'activerecord.attributes.public_comment')} #{public_comment.licensee_name}"
              .secondary-content
                %a{:href => public_comment_path(public_comment)}
                  %i.material-icons pageview
                %a{:href => edit_public_comment_path(public_comment)}
                  %i.material-icons edit
                %a{"href" => public_comment_path(public_comment), "rel" => "nofollow", "data-method" => "delete", "data-confirm" => t(:confirm_delete)}
                  %i.material-icons delete
      .card-action
        = link_to t(:new), new_public_comment_path

app/views/public_comments/new.html.haml
.row
  .col.s6.offset-s3
    .card
      .card-content.deep-purple
        .card-title.white-text
          %h1= t(:new) + t(:public_comment, scope: 'activerecord.models')
      .card-content
        = render partial: 'form', locals: {back_link: public_comments_path, form_url: public_comments_path, form_method: :post}

app/views/public_comments/show.html.haml
.row
  .col.s6.offset-s3
    .card
      .card-content.deep-purple
        .card-title.white-text
          =t(:public_comment, scope: 'activerecord.models')
          =@public_comment.id
      .card-content
        .section
          %h6= t(:route_no, scope: 'activerecord.attributes.public_comment')
          = @public_comment.route_no
        .section
          %h6= t(:route, scope: 'activerecord.attributes.public_comment')
          = @public_comment.route&.name
        .section
          %h6= t(:car_plate, scope: 'activerecord.attributes.public_comment')
          = @public_comment.car_plate
        .section
          %h6= t(:car, scope: 'activerecord.attributes.public_comment')
          = @public_comment.car&.chassis
        .section
          %h6= t(:licensee_name, scope: 'activerecord.attributes.public_comment')
          = @public_comment.licensee_name
        .section
          %h6= t(:licensee, scope: 'activerecord.attributes.public_comment')
          = @public_comment.licensee&.license_no
        .section
          %h6= t(:comment, scope: 'activerecord.attributes.public_comment')
          = @public_comment.comment
        .section
          %h6= t(:commenter_name, scope: 'activerecord.attributes.public_comment')
          = @public_comment.commenter_name
        .section
          %h6= t(:commenter_contact, scope: 'activerecord.attributes.public_comment')
          = @public_comment.commenter_contact
        .section
          %h6= t(:commenter_address, scope: 'activerecord.attributes.public_comment')
          = @public_comment.commenter_address
        .section
          %h6= t(:updated_at)
          = l(@public_comment.updated_at, format: :long, default: nil)

      .card-action
        = link_to t(:edit), edit_public_comment_path(@public_comment)
        = link_to t(:back), public_comments_path